remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: neon
locale: pt-BR
title: Curso de Drupal
title_separator: '|'
name: Curso de Drupal
description: >-
  Os cursos são preparados para um número reduzido de pessoas e ministrados
  exclusivamente online.
url: 'https://cursodedrupal.com.br'
baseurl: '/'
repository: xulispa/curso-de-drupal
email: contato@cursodedrupal.com.br
head_scripts:
  - 'https://code.jquery.com/jquery-3.6.0.min.js'
breadcrumbs: true
twitter:
  username: drupaldecurso
github_username: xulispa
search: true
search_full_content: true
search_provider: lunr
lunr:
  search_within_pages: true
  files_to_exclude:
    - _pages/404.md
    - _pages/category-archive.md
    - _pages/contact.md
    - _pages/tag-archive.md
    - _pages/year-archive.md
logo: /assets/images/logo.png
og_image: /assets/images/1200x1200.png
analytics:
  provider: google-gtag
  google:
    tracking_id: UA-34092520-1
    anonymize_ip: false
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
timezone: America/Sao_Paulo
include:
  - _pages
  - _courses
  - _free
  - _extra
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
atom_feed:
  hide: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache
  - jekyll-target-blank
  - jekyll-watch
  - jekyll-lunr-js-search
  - jekyll-youtube
  - octopress
author:
  links:
    - label: Drupal.org
      icon: fab fa-fw fa-drupal
      url: 'https://drupal.org/u/xulispa'
    - label: YouTube
      icon: fab fa-fw fa-youtube
      url: 'https://www.youtube.com/cursodedrupal'
    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: 'https://www.linkedin.com/in/xulispa'
    - label: Github
      icon: fab fa-fw fa-github
      url: 'https://www.github.com/xulispa'
    - label: Email
      icon: fas fa-fw fa-at
      url: 'mailto:contato@cursodedrupal.com.br'
footer:
  links:
    - label: Drupal.org
      icon: fab fa-fw fa-drupal
      url: 'https://drupal.org/u/xulispa'
    - label: YouTube
      icon: fab fa-fw fa-youtube
      url: 'https://www.youtube.com/cursodedrupal'
    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: 'https://www.linkedin.com/in/xulispa'
    - label: Github
      icon: fab fa-fw fa-github
      url: 'https://www.github.com/xulispa'
    - label: Email
      icon: fas fa-fw fa-at
      url: 'mailto:contato@cursodedrupal.com.br'
defaults:
  - scope:
      path: _courses
      type: courses
    values:
      layout: courses
      author_profile: false
      share: true
      classes:
        - wide
      sidebar:
        nav: courses
  - scope:
      path: _free
      type: free
    values:
      layout: free
      author_profile: false
      share: true
      classes:
        - wide
      sidebar:
        nav: free
  - scope:
      path: _extra
      type: extra
    values:
      layout: free
      author_profile: false
      share: true
      classes:
        - wide
      sidebar:
        nav: free
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true
      classes:
        - wide
collections:
  courses:
    output: true
    permalink: '/:collection/:path/'
  free:
    output: true
    permalink: '/:collection/:path/'
  extra:
    output: true
    permalink: '/:collection/:path/'
