# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Curso de Drupal
title_separator: |
name: "Curso de Drupal"
url: "https://cursodedrupal.com.br"
baseurl: ""
repository: "xulispa/curso-de-drupal"
email: xulispa@xulispa.com.br

head_scripts:
  - https://code.jquery.com/jquery-3.2.1.min.js
  - /assets/js/curso-de-drupal-head.js

description: >- # this means to ignore newlines until "baseurl:"
  Os cursos são preparados para um número reduzido de pessoas e ministrados exclusivamente online.

locale: pt-BR

twitter_username: drupaldeelite
github_username: xulispa
facebook:
  app_id: 317464955533272 # A Facebook app ID
  publisher: drupaldeelite # A Facebook page URL or ID of the publishing entity
  username: "drupaldeelite"  # https://www.facebook.com/michaelrose

minimal_mistakes_skin: neon
search: true
search_full_content: true

logo: /assets/images/logo.png
og_image: /assets/images/logo.png

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-34092520-1"
    anonymize_ip: false # default

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

timezone: America/Sao_Paulo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _posts
  - _courses

atom_feed:
  hide: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  links:
    - label: "Drupal.org"
      icon: "fab fa-fw fa-drupal"
      url: "https://drupal.org/u/xulispa"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/cursodedrupal"
    - label: "Email"
      icon: "fas fa-fw fa-at"
      url: "mailto:xulispa@xulispa.com.br"

footer:
  links:
    - label: "Drupal.org"
      icon: "fab fa-fw fa-drupal"
      url: "https://drupal.org/u/xulispa"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/cursodedrupal"
    - label: "Email"
      icon: "fas fa-fw fa-at"
      url: "mailto:xulispa@xulispa.com.br"

defaults:
  # _courses
  - scope:
      path: ""
      type: courses
    values:
      layout: single
      author_profile: true
      share: true
      classes:
        - wide
      sidebar:
        nav: "courses"
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes:
        - wide
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      classes:
        - wide

category_archive:
  type: liquid
  path: /categorias/
tag_archive:
  type: liquid
  path: /tags/

collections:
  courses:
    output: true
    permalink: /:collection/:path/