title: Curso de Drupal
title_separator: '|'
name: Curso de Drupal
url: 'https://cursodedrupal.com.br'
baseurl: ''
repository: xulispa/curso-de-drupal
email: xulispa@xulispa.com.br
head_scripts:
  # - 'https://code.jquery.com/jquery-3.2.1.min.js'
  # - /assets/js/curso-de-drupal-head.js
description: >-
  Os cursos são preparados para um número reduzido de pessoas e ministrados
  exclusivamente online.
locale: pt-BR
twitter_username: drupaldeelite
github_username: xulispa
# facebook:
#   app_id: 317464955533272
#   publisher: drupaldecurso
#   username: drupaldecurso
minimal_mistakes_skin: neon
search: true
search_full_content: true
logo: /assets/images/logo.png
og_image: /assets/images/1200x1200.png
analytics:
  provider: google-gtag
  google:
    tracking_id: UA-34092520-1
    anonymize_ip: false
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: '/:categories/:title/'
paginate: 5
paginate_path: '/page:num/'
timezone: America/Sao_Paulo
include:
  - _pages
  - _posts
  - _courses
atom_feed:
  hide: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-target-blank
  - jekyll-watch
author:
  links:
    - label: Drupal.org
      icon: fab fa-fw fa-drupal
      url: 'https://drupal.org/u/xulispa'
    - label: YouTube
      icon: fab fa-fw fa-youtube
      url: 'https://www.youtube.com/cursodedrupal'
    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: 'https://www.linkedin.com/in/xulispa'
    - label: Github
      icon: fab fa-fw fa-github
      url: 'https://www.github.com/xulispa'
    - label: Email
      icon: fas fa-fw fa-at
      url: 'mailto:xulispa@xulispa.com.br'
footer:
  links:
    - label: Drupal.org
      icon: fab fa-fw fa-drupal
      url: 'https://drupal.org/u/xulispa'
    - label: YouTube
      icon: fab fa-fw fa-youtube
      url: 'https://www.youtube.com/cursodedrupal'
    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: 'https://www.linkedin.com/in/xulispa'
    - label: Github
      icon: fab fa-fw fa-github
      url: 'https://www.github.com/xulispa'
    - label: Email
      icon: fas fa-fw fa-at
      url: 'mailto:xulispa@xulispa.com.br'
defaults:
  - scope:
      path: ''
      type: courses
    values:
      layout: courses
      author_profile: false
      share: true
      classes:
        - wide
      sidebar:
        nav: courses
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes:
        - wide
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true
      classes:
        - wide
category_archive:
  type: liquid
  path: /categorias/
tag_archive:
  type: liquid
  path: /tags/
collections:
  courses:
    output: true
    permalink: '/:collection/:path/'
jekyll_admin:
  homepage: pages
